source 'https://cdn.cocoapods.org/'
source 'https://github.com/CruGlobal/cocoapods-specs.git'

platform :ios, '14.0'

use_modular_headers!

target 'MPDXClientExampleCocoapods' do

  pod 'MPDXiOSLib', '~> 0.6.7'
end