name: Build App

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'

      - name: MPDXiOSLib SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MPDX_IOS_LIB_SSH_PRIVATE_KEY }}

      - name: Bundle Install
        run: bundle install

      - name: Import App Store Connect API Key
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          APP_STORE_CONNECT_API_JSON_PAYLOAD: ${{ secrets.APP_STORE_CONNECT_API_JSON_PAYLOAD }}
        run: echo $APP_STORE_CONNECT_API_JSON_PAYLOAD > fastlane/AppleAppStoreApi.json

      - name: Increment Xcode Project Build Number
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: bundle exec fastlane cru_shared_lane_increment_xcode_project_build_number

      - name: Build And Deploy For TestFlight Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          MATCH_GIT_BASIC_AUTHORIZATION_PAT: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane cru_shared_lane_build_and_deploy_for_testflight_release is_running_in_ci:true
